name: Troubleshooting Lab CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      TestHost:
        description: 'Host to run the net probe script against'
        required: true
        default: 'github.com'
      InodesUsageThreshold:
        description: 'Threshold for inodes usage percentage to trigger a warning'
        required: true
        default: '80'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linter check
        run: |
          echo "Running linter..."
          shellcheck linux/scripts/*.sh

      - name: Run net probe script
        run: |
          echo "Running CI script..."
          ./linux/scripts/net_probe.sh ${{ github.event.inputs.TestHost }}
      - name: Run system health script
        run: |
          echo "Running system health check..."
          ./linux/scripts/system_health.sh ${{ github.event.inputs.InodesUsageThreshold }}
